# Generated by Django 4.1.2 on 2022-11-16 12:50

import django.core.validators
from django.db import migrations, models
import petstagram.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[petstagram.core.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[petstagram.core.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
