version: '3.4'

services:
  web:
    image: vladiliev/petstagram_app
    build: .
    command: gunicorn petstagram.wsgi:application --bind 0.0.0:8000
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./media:/home/app/web/media
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: petstagram_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 81:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./media:/home/app/web/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web